language: node_js
node_js:
  - "10.14.1"
cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
- npm update

install:
- npm install

script:
- npm test

after_success:
- npm run test:coverage
